### ISSUE TITLE
shell 3.14 compatability?

### ISSUE THREAD

**Issue by ghost** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#11]

**Comment by franglais125** [comment]
I think you can install it from here:
https://extensions.gnome.org/extension/887/workspace-isolated-dash/

**Comment by N-Yuki** [comment]
Thanks for responding to this, @franglais125. You've been super helpful.

I'll just add you can find past versions of this extension (which will support older gnome shell versions) under releases/tags of this repository. I'm on my phone, and can't find the link right now though unfortunately.

**Comment by franglais125** [comment]
Ah, good idea!, I didn't think of tags. Here is the link for what @N-Yuki is saying:
https://github.com/N-Yuki/gnome-shell-extension-workspace-isolated-dash/releases

The latest version to support 3.14 is v6.

To be clear: from v6_1 support is dropped!

**Comment by N-Yuki** [comment]
This issue should be resolved now. Feel free to reopen if something is still unclear.
