### ISSUE TITLE
Does not work in Gnome 3.26

### ISSUE THREAD

**Issue by darkdragon-001** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#13]
I tried this extension in Ubuntu 17.10 with Gnome 3.26 and I don't see any effect.

What I did?
1. added verion `3.26` to metadata.json
2. `sudo make install`
3. relogin _(Wayland does not support Gnome restart)_
4. enable extension in Gnome Tweak Tool
5. relogin

Can anyone help me with this issue?

**Comment by N-Yuki** [comment]
Thanks for reporting this. I haven't updated or used this extension in a while, but can you also test this on X11 too? It probably doesn't make a difference, but could be helpful to know.

If it is an incompatibility with 3.26, I'd need to know what was changed for this to stop working and I'm away from my gnome shell desktop system for a couple of months, so I can't test it myself right now.

**Comment by franglais125** [comment]
I just tested this on Gnome 3.26 in a Xorg session, and it works fine, no errors in the logs either.

@darkdragon-001 can you check if your logs show any relevant errors?

`sudo journalctl /usr/bin/gnome-shell`

When I finish a few things here I'll test a Wayland session as well.

**Comment by darkdragon-001** [comment]
I wasn't really aware of what this extension does and about the names since I freshly switched from Unity a few days ago.

There are the words _dash_, _dock_, _app switcher_, ...

- **Dash _(or whatever is launched when pressing "Activities" or `Super` key)_**: Apps are separated by workspace (also without the extension activated)
- **Dock _(or however the left bar with the app icons is called)_**: favorites and running apps (any workspace) are shown here always and the same for every workspace
- **Alt+Tab app switcher**: isolate workspaces via gconf: _org > gnome > shell > app-switcher > `true`_

I assume that this extension should separate the _dock_ for the workspaces (show only favorites and applications with window on a workspace), adjust window indicator _(little dots for running windows)_ and so on.

Is this assumption correct?

@franglais125 I couldn't find any errors corresponding to the extension in the logs...

**Comment by N-Yuki** [comment]
I believe you are mostly correctly. Favorites will be shown in all workspaces however.

Also, there is no Dock in Gnome Shell by default.
Are you using other extensions? In particular, Dash to Dock? Dash to Dock isn't compatible with this extension and they implement their own version of this functionality, which is configurable in their own extension settings.

**Comment by darkdragon-001** [comment]
By default, the following extensions are installed:
- Ubuntu appindicators _(modified version of kstatusmodifiericon/appindicator)_
- Ubuntu dash _(modified version of dash to dock)_

Is there any plan to add support for Dash to Dock?

**Comment by N-Yuki** [comment]
There is no need to support Dash to Dock since they implement their own version of workspace isolation that you can enable from the extension's options/settings.

Try take a look at the options for Ubuntu Dash, and see if they also have their own isolation setting.

**Comment by darkdragon-001** [comment]
Ubuntu dash does not have an options page, but tells in the comment to install Dash to Dock if you want these options. This is what I did, changed the defaults so that they match the ones from Ubuntu and it works :) Thanks for the hint! 

According to @franglais125 this plugin seems to work for version 3.26 (Wayland testing still outstanding). So just adding the version to the `metafile.json` should add the corresponding support.

**Comment by N-Yuki** [comment]
@darkdragon-001 Glad to hear you were able to get it working :)

@fraglais125 Thanks for doing the tests!

If anyone wants to make a pull request with the metadata changes, I'm happy to accept it.
And then I'll upload it to the extensions site.
I wasn't sure if anyone was still interested in using this extension when a lot of people seem to have Dash to Dock installed now, which is fundamentally incompatible since they completely replace the Dash implementation while my extension modifies the default Dash in place.

**Comment by N-Yuki** [comment]
Sorry, I meant @franglais125

**Comment by N-Yuki** [comment]
metadata.json updated in commit 1edf2730203aeb8ce20ef84c6249f71f857cf350

If there is a Wayland issue, a new issue can be opened.
