### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by drozel** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#16]
Ubuntu 18.04. Gnome 3.28, extension not working: neither red points on favourited apps (shows common count of instances on all workspaces, see screenshots 1 and 2) not regular apps (shows icon of an instance opened on antother workspace, screenshots 3,4)

**Situation1**: 2 chrome instances opened each in the own workspace, but both whowing two instance counter points 

**Situation2**: nautilus (trash folder) opened on the first workspace only, but shown on both bars
**first workspace:**
![screen1](https://user-images.githubusercontent.com/6229397/42559666-07433a1c-84f5-11e8-8977-402d4a0160b0.png)
 **second workspace:**
![screen2](https://user-images.githubusercontent.com/6229397/42559667-0762fcd0-84f5-11e8-828b-46cbd744e943.png)

**Comment by N-Yuki** [comment]
Hi @drozel . Thanks for the the report.

However, that dock being used does not look like the Gnome Dash, so it is possible that the dock used in Ubuntu is written from scratch and implements its own app counting system, which can break compatibility with this extension. I would suggest looking to see if the Ubuntu dock has its own settings for workspace isolation.

If it was working on a previous version of Gnome Shell, then it may be something I need to correct on this side though.

**Comment by drozel** [comment]
Ok, thanks.
Sorry, i removed the first 2 screenshots because of sensitive information. If you need reports to fix it, i'm ready to help

**Comment by franglais125** [comment]
As the author mentioned, it looks like you are using Dash-to-Dock or Ubuntu-dock.

@drozel can you try running the following? It should activate the isolation.

```
dconf write /org/gnome/shell/extensions/dash-to-dock/isolate-workspaces true
```

Note that this is independent of @N-Yuki 's extension!

**Comment by drozel** [comment]
@franglais125 thank you very much! it working!
