### ISSUE TITLE
Error on gnome 3.36

### ISSUE THREAD

**Issue by jacobmischka** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#21]
Tracking issue for updating for gnome 3.36.

I'll try to dig into it soon and hopefully put together a PR.

**Comment by jdloft** [comment]
Sorry, I meant to say 3.36 in the first PR

**Comment by blipk** [comment]
I have fixed this in my extension here, should work with any version: 
https://github.com/blipk/worksets/
https://extensions.gnome.org/extension/1583/worksets/

If you would still like to you nyukis extension, you can replace extension.js with workspaceIsolater.js from my extension, and change Me.gWorkspaceManager on line 125 to global.workspace_manager
