### ISSUE TITLE
Request to accept the extension ports and upload it to the gnome extensions website

### ISSUE THREAD

**Issue by vendillah** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#26]
This extension is exactly what people are looking for, but deemed incompatible. Here is a list of all threads and posts of people wondering how to get the dock behavior (from dash to dock) without dropping the dash.

- [Super+Number opens that app in the pinned dock. Is there a keybinding to open a new instance?](https://redlib.freedit.eu/r/gnome/comments/yb3kid/supernumber_opens_that_app_in_the_pinned_dock_is/) on reddit.
- [Anonymized thread](https://reddit.invak.id/r/gnome/comments/138w6ef/new_instance_dash_keyboard_shortcut_workspace/) on reddit.
- [Another anonymized thread](https://libreddit.privacydev.net/r/gnome/comments/r1n60b/is_there_a_keyboard_shortcut_to_launch_a_new/) on reddit.
- [Launch new instance when there is no instance open on current workspace (without extensions)](https://redlib.freedit.eu/r/gnome/comments/qa15q1/launch_new_instance_when_there_is_no_instance/) on reddit.
- [How do I open a new instance of an application by default in GNOME?](https://askubuntu.com/questions/125243/how-do-i-open-a-new-instance-of-an-application-by-default-in-gnome) on Ask Ubuntu.
- [How to open new window instead of already open window in gnome [duplicate]](https://askubuntu.com/questions/579568/how-to-open-new-window-instead-of-already-open-window-in-gnome) on Ask Ubuntu.
- [gnome-shell shortcut for opening new instance](https://superuser.com/questions/280092/gnome-shell-shortcut-for-opening-new-instance) on Super User (though outdated).
- [Make new instance of application open in current desktop](https://unix.stackexchange.com/questions/723548/make-new-instance-of-application-open-in-current-desktop).

They are all hinting towards the same problem (creating a new window instance) for which this extension provides a solution (regardless of windows opened in other workspaces). At this moment, no extension could be found for my desktop environment (Gnome 42) that solves this. Mainly because the extension appears not to be maintained anymore. A few pull requests have ported it however.

- [jdloft ported it to 3.30](https://github.com/jdloft/gnome-shell-extension-workspace-isolated-dash)
- [wakira continued that work to port it to more recent versions, including 42](https://github.com/wakira/gnome-shell-extension-workspace-isolated-dash)

Unfortunately, the updates have not reached the main repository, nor the extensions website. For now, I had to install the latest manually by downloading a zip of the project, renaming its directory and moving it to `~/.local/share/gnome/shell/extensions`. Even finding how to install an extension manually took me a while. (For reference, here is [the tutorial I followed](https://www.pragmaticlinux.com/2021/06/manually-install-a-gnome-shell-extension-from-a-zip-file/).) I'm sure others would have given up by now.

I request to integrate these updates and update the website, or make the repository independent of a user, so that if somebody loses interest, someone else can take over. The community appears to be interested in such a simple extension, since gnome doesn't provide such options upstream, so it's definitely worth keeping this project alive, by whoever.

**Comment by N-Yuki** [comment]
Thanks for the feedback.

As you pointed out, other people have forked this codebase, and they are free to upload it to the Gnome extension website as a new entry, so it should already be possible for other people to pick up this project.

You have a point about making the author independent of a single person, so updates can be applied without relying on new entries on the Gnome extension website every time there is an author change, but this would still require a shared profile on the Gnome extension website that would upload this extension. This would introduce security risks if anyone could upload an update to this extension.

I am happy to try apply the changes made in these forks and upload them for review on the extension website for now, but I'm not sure if there is a simple solution of keeping this extension updated

**Comment by N-Yuki** [comment]
I uploaded a version with up to Gnome 44 compatibility (pending review on Gnome's side), but I see that another project has picked up this feature:

https://github.com/N-Yuki/gnome-shell-extension-workspace-isolated-dash/issues/24#issuecomment-618318557
https://extensions.gnome.org/extension/1583/worksets/
https://github.com/blipk/Customised-Workspaces

From 45, there appears to be a large change that impacts extension compatibility, so it would be better to switch to the above extension which appears to still be maintained properly.

**Comment by vendillah** [comment]
Thanks for your quick reply and updates to the code!

I had that extension already installed and had tried it way back on my old gnome version 3.38, which wasn't a good experience. While looking for extensions after my recent Gnome upgrade, I thus viewed installed disabled extensions that I had tried long time ago as noise in my searches. (Ironically, I didn't delete them, so I'd be aware of the project.) Anyway, thanks for reminding me that the functionality is also available through the Customized Workspaces extension. I will be using that one from now on.

We 'd indeed still have a single point of failure when uploading the extension to Gnome's website, as no other active maintainers seem present. May I suggest that, since this repository is in passive maintenance, and there is already another extension doing the job, this repository gets archived? The README could then also be updated to redirect rabbit-hole searchers like myself to the more actively maintained Customized Workspaces extension right away, and to list some known bugs.

I believe the breaking change in Gnome 45 is the move to ES6 that disallows old styled imports, which can be replaced by the modern styled imports, but I may be wrong. It will take time programming, testing and uploading if all goes well and it works first try.

As for the known bug: Workspace Isolated Dash works most of the time (in Gnome 42 on Zorin OS 17). I encountered a few times (in past three days) that it switches to an application inside another workspace, but I've discovered the exact same problem with Customized Workspaces (once). And the few times that it occurs, it's fixed by closing all instances of an application.

I'll close this as soon as I get to test the extension and provide feedback. It is currently not available yet.

---

Edit: It appears their extension has a bug, where it messes up the preview of workspaces. All the previews are empty no matter what I try (restart, logout) - perhaps that was my issue back then as well. It appears I won 't make the transition as soon then :p

**Comment by vendillah** [comment]
Well, interestingly, the extension manager showed that I already had the updated version installed, but I reinstalled it to be sure, and it works :tada: I'm closing this issue.

I do complement my previous note with the fact that this extension does show the applications in preview, but doesn't show the background - which is fine to me. More importantly, it is much more performant than the other. When I switch to overview, it simply lags, whereas this extension doesn't affect the smooth transitions.

I'd be interested in co-maintaining this extension, given its performance and simplicity, but there are a few other projects I want to work on as well, so it will definitely not be in the near future.
