### ISSUE TITLE
Update to 3.18

### ISSUE THREAD

**Issue by aurelien-naldi** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#6]
After adding version 3.18 to the metadata, it loads and works well for me

**Comment by N-Yuki** [comment]
I haven't jumped over to 3.18 yet, but have you noticed any new issues or does it work the same with the changed metadata?

**Comment by aurelien-naldi** [comment]
I have been using it for a while now and I didn't notice any problem

**Comment by N-Yuki** [comment]
Thanks. I've tagged and uploaded a new version with the updated metadata.
