### ISSUE TITLE
Wayland: dash not refreshed when switching to empty workspace

### ISSUE THREAD

**Issue by franglais125** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#8]
Hi @N-Yuki :

I have a small Wayland issue to report. When switching to an empty workspace (with no windows), the dash is not refreshed. My guess is that `this._onRestackedId = global.screen.connect('restacked', WorkspaceIsolator.refresh);` is not enough, since there `restacked` signal never happens.
Maybe another connection is needed?

Steps to reproduce:
- Open a Wayland session
- Open a non-favorite app
- Switch to an empty workspace

Problem: the running app is still displayed.

**Comment by franglais125** [comment]
Adding this solved the issue for me:

`global.window_manager.connect('switch-workspace', WorkspaceIsolator.refresh);`

**Comment by N-Yuki** [comment]
Thanks for finding this issue. I've pushed the change to git, and I'll be pushing it up onto the Gnome Extension site too. I was in the review process of another push to the Gnome Extension site, simplify the codebase, so there will probably be 2 consecutive updates coming there soon.

**Comment by franglais125** [comment]
Yeah, I noticed you had pushed some updates to the Extension site. (https://extensions.gnome.org/review/)
Thanks a lot for the quick replies and updates!

Since you removed the `installed-changed` signal, maybe this will help with RAM?
I have an extra laptop (not with me now) that is still affected by the RAM issue, so I will test this update whenever I get the chance (if that was the intention).
